## Rubric

Instructions: DELETE this cell before you submit via a `git push` to your repo before deadline. This cell is for your reference only and is not needed in your report. 

 Scoring: Out of 10 points

- Each Developing  => -2 pts
- Each Unsatisfactory/Missing => -4 pts
  - until the score is 0

If students address the detailed feedback in a future checkpoint they will earn these points back






|                                  | **Unsatisfactory**                                                                                                                                                                                                                                                                                                                        | **Developing**                                                                                                                                                                                                       | **Proficient**                                                                                                                                                                                            | **Excellent**                                                                                                                                                                            |
|----------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **EDA relevance**                | EDA is mostly neither relevant to the question nor helpful in figuring out how to address the question. Or the EDA does address the question, but many obviously relevant variables / analyses / figures were not included. | EDA is partly irrelevant/unhelpful. EDA missed one or two obvioulsy relevant analysis (distributions of single variables or relationships between variables) | EDA includes the obviously relevant / helpful variables in addressing the question.                                                              | Thorough EDA fully explored the dataset                                                                                                                 |
| **EDA analysis and description** | Many of the analyses are poor choices (e.g., using means instead of medians for obviously skewed data), or are poorly described in the text, or do not aid understanding the data                                                                                                                                                     | Some of the analyses are poor choices, or are poorly described in the text, or do not aid understanding the data                                                                                                 | All analyses are correct choices. Only one or two have minor issues in the text descriptions supporting them. Mostly they fit well with other elements of the EDA and support understanding the data  | All analyses are correct choices with clear text descriptions supporting them. The figures fit well with the other elements of the EDA, producing a clear understanding of the data. |
| **EDA figures**                  | Many of the figures are poor plot choices (e.g., using a bar plot to represent a time series where it would be better to use a line plot) or have poor aesthetics (including colormap, data point shape/color, axis labels, titles, annotations, text legibility) or do not aid understanding the data                                | Some of the figures are poor plot choices or have poor aesthetics. Some figures do not aid understanding the data                                                                                                | All figures are correct plot choices. Only one or two have minor questionable aesthetic choices. The figures mostly fit well with the other elements of the EDA and support understanding the data    | All figures are correct plot choices with beautiful aesthetics. The figures fit well with the other elements of the EDA, producing a clear understanding of the data.                |

# COGS 108 - EDA Checkpoint

## Authors

Instructions: REPLACE the contents of this cell with your team list and their contributions. Note that this will change over the course of the checkpoints

This is a modified [CRediT taxonomy of contributions](https://credit.niso.org). For each group member please list how they contributed to this project using these terms:
> Analysis, Background research, Conceptualization, Data curation, Experimental investigation, Methodology, Project administration, Software, Visualization, Writing – original draft, Writing – review & editing

Example team list and credits:
- Alice Anderson: Conceptualization, Data curation, Methodology, Writing - original draft
- Bob Barker:  Analysis, Software, Visualization
- Charlie Chang: Project administration, Software, Writing - review & editing
- Dani Delgado: Analysis, Background research, Visualization, Writing - original draft

# Research Question

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your proposal feedback

## Background and Prior Work

Coral reefs are highly sensitive marine ecosystems that provide important ecological, economic, and coastal protection benefits. In recent years, coral reef health has declined worldwide due to rising sea surface temperatures, more frequent marine heatwaves, and local stressors such as algal overgrowth. Thermal stress, often measured using Degree Heating Weeks (DHW), is strongly linked to coral bleaching events, which can lead to partial or complete loss of live coral cover. <a name="cite_ref-1"></a>[<sup>1</sup>](#cite_note-1) While many studies document coral decline following thermal stress, less is known about how coral reefs recover over time and weather recovery follows consistent patterns across different sites.  <a name="cite_ref-2"></a>[<sup>2</sup>](#cite_note-2)

Being students of University of California, San Diego, part of our academic environment is ingrained with the university’s strengths in marine biology, oceanography, and climate science through programs such as the Scripps Institution of Oceanography. UC San Diego researchers have made major contributions to coral reef monitoring and the study of climate-driven marine stressors, which does add to the motivation for this project. Publicly available datasets from organizations like NOAA and the National Coral Reef Monitoring Program align well with UC San Diego’s emphasis on data-driven marine science and provide a strong foundation for this analysis.

Previous research has shown that coral recovery trajectories can vary widely depending on environmental conditions and local ecological dynamics. Studies using NOAA Coral Reef Watch data have found that higher DHW values are associated with more severe bleaching and increased coral mortality, often resulting in slow or incomplete recovery. <a name="cite_ref-3"></a>[<sup>3</sup>](#cite_note-3) However, more recent monitoring efforts, such as the National Coral Reef Monitoring Program (NCRMP), provide long-term, site-level data on percent live coral and algal cover across U.S. reef systems. <a name="cite_ref-4"></a>[<sup>4</sup>](#cite_note-4)

While many studies using these data focus on overall trends in reef health, fewer explicitly examine differences in recovery pathways over time. Our project builds on this prior work by identifying coral recovery trajectories and analyzing how thermal stress and algal cover, both individually and together, are associated with differences in recovery outcomes across U.S. coral reef sites.


1. <a name="cite_note-1"></a> [^](#cite_ref-1) Watch, N. C. R. (n.d.). Coral Reef Watch Home. NOAA Coral Reef Watch Daily 5km Satellite Coral Bleaching Heat Stress Monitoring Products (Version 3.1). https://coralreefwatch.noaa.gov/product/5km/index.php  
2. <a name="cite_note-2"></a> [^](#cite_ref-2) Hughes et Al. (2017, March 16). Global warming and recurrent mass bleaching of corals. Nature News. https://www.nature.com/articles/nature21707 
3. <a name="cite_note-3"></a> [^](#cite-ref-3)Liu, G. et Al. (2014, November 20). Reef-scale thermal stress monitoring of coral ecosystems: New 5-km global products from NOAA Coral Reef Watch. MDPI. https://www.mdpi.com/2072-4292/6/11/11579 
4. <a name="cite_note-4"></a> [^](#cite-ref-4)National Coral Reef Monitoring Program: Tracking Environmental Conditions. NCRMP | Environmental. (n.d.). https://coralreef.noaa.gov/topics/national-coral-reef-monitoring-program/environmental

# Hypothesis

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your proposal feedback

## Data

### Data overview

In [1]:
# Run this code every time when you're actively developing modules in .py files.  It's not needed if you aren't making modules
#
## this code is necessary for making sure that any modules we load are updated here 
## when their source code .py files are modified

%load_ext autoreload
%autoreload 2

In [2]:
# Setup code -- Run only once after cloning!!! 
#
# this code downloads the data from its source to the `data/00-raw/` directory
# if the data hasn't updated you don't need to do this again!

# if you don't already have these packages (you should!) uncomment this line
# %pip install requests tqdm

import sys
sys.path.append('./modules') # this tells python where to look for modules to import

import get_data # this is where we get the function we need to download data

# replace the urls and filenames in this list with your actual datafiles
# yes you can use Google drive share links or whatever
# format is a list of dictionaries; 
# each dict has keys of 
#   'url' where the resource is located
#   'filename' for the local filename where it will be stored 
datafiles = [
    { 'url': 'https://raw.githubusercontent.com/fivethirtyeight/data/refs/heads/master/airline-safety/airline-safety.csv', 'filename':'airline-safety.csv'},
    { 'url': 'https://raw.githubusercontent.com/fivethirtyeight/data/refs/heads/master/bad-drivers/bad-drivers.csv', 'filename':'bad-drivers.csv'}
]

get_data.get_raw(datafiles,destination_directory='data/00-raw/')

Overall Download Progress:   0%|          | 0/2 [00:00<?, ?it/s]
Downloading airline-safety.csv:   0%|          | 0.00/1.23k [00:00<?, ?B/s]
Overall Download Progress:  50%|█████     | 1/2 [00:00<00:00,  7.10it/s]

Successfully downloaded: airline-safety.csv

Downloading bad-drivers.csv:   0%|          | 0.00/1.37k [00:00<?, ?B/s]
Overall Download Progress: 100%|██████████| 2/2 [00:00<00:00,  4.06it/s]

Successfully downloaded: bad-drivers.csv

### Dataset #1 

## Florida NCRMP Benthic Cover Data

This dataset contains benthic cover observations from Florida reef monitoring sites collected under the National Coral Reef Monitoring Program (NCRMP).

The dataset includes 13,602 observations and 35 variables. Important variables for our analysis include:

- PRIMARY_SAMPLE_UNIT: Unique reef site identifier  
- LATITUDE and LONGITUDE: Geographic coordinates used to match sites to thermal grid data  
- YEAR: Survey year  
- REGION: Geographic region classification  
- COVER_CAT_NAME: Organism category (coral vs algae)  
- HARDBOTTOM_P: Percent hardbottom cover (used to compute total coral and algae percentages)

Percent cover values represent the proportion of reef surface covered by different organism categories.

One limitation of this dataset is uneven monitoring across sites and missing values in certain habitat and substrate variables.

In [3]:
import pandas as pd

florida = pd.read_csv("data/00-raw/CRCP_Benthic_Cover_Florida_7018_0ee5_9488.csv")

print(florida.shape)
florida.head()
florida.isnull().sum()

(13602, 35)

time                       0
latitude                   0
longitude                  0
REGION                     1
PRIMARY_SAMPLE_UNIT        1
STATION_NR                 1
YEAR                       1
MONTH                      1
DAY                        1
Date_UTC                   0
HABITAT_CD                 4
HABITAT_TYPE              51
STRAT                     24
Description             4854
RUGOSITY_CD            10142
WTD_RUG                 6556
MAPGRID_NR                 1
SUB_REGION_NAME            1
SUB_REGION_NR              1
ZONE_NAME               3461
ZONE_NR                 3461
MPA_NAME                3461
MPA_NR                     1
ADMIN                  13602
PROT                       1
DEPTH_STRAT             8749
MIN_DEPTH                 29
MAX_DEPTH                 29
METERS_COMPLETED          29
COVER_CAT_CD              30
COVER_CAT_NAME            30
HARDBOTTOM_P              29
SOFTBOTTOM_P              29
RUBBLE_P                  29
accession_url              1
dtype: int64

In [4]:

florida = pd.read_csv("data/00-raw/CRCP_Benthic_Cover_Florida_7018_0ee5_9488.csv")

print(florida.shape)
florida.head()
florida.isnull().sum()

(13602, 35)

time                       0
latitude                   0
longitude                  0
REGION                     1
PRIMARY_SAMPLE_UNIT        1
STATION_NR                 1
YEAR                       1
MONTH                      1
DAY                        1
Date_UTC                   0
HABITAT_CD                 4
HABITAT_TYPE              51
STRAT                     24
Description             4854
RUGOSITY_CD            10142
WTD_RUG                 6556
MAPGRID_NR                 1
SUB_REGION_NAME            1
SUB_REGION_NR              1
ZONE_NAME               3461
ZONE_NR                 3461
MPA_NAME                3461
MPA_NR                     1
ADMIN                  13602
PROT                       1
DEPTH_STRAT             8749
MIN_DEPTH                 29
MAX_DEPTH                 29
METERS_COMPLETED          29
COVER_CAT_CD              30
COVER_CAT_NAME            30
HARDBOTTOM_P              29
SOFTBOTTOM_P              29
RUBBLE_P                  29
accession_url              1
dtype: int64

In [5]:
florida.columns

Index(['time', 'latitude', 'longitude', 'REGION', 'PRIMARY_SAMPLE_UNIT',
       'STATION_NR', 'YEAR', 'MONTH', 'DAY', 'Date_UTC', 'HABITAT_CD',
       'HABITAT_TYPE', 'STRAT', 'Description', 'RUGOSITY_CD', 'WTD_RUG',
       'MAPGRID_NR', 'SUB_REGION_NAME', 'SUB_REGION_NR', 'ZONE_NAME',
       'ZONE_NR', 'MPA_NAME', 'MPA_NR', 'ADMIN', 'PROT', 'DEPTH_STRAT',
       'MIN_DEPTH', 'MAX_DEPTH', 'METERS_COMPLETED', 'COVER_CAT_CD',
       'COVER_CAT_NAME', 'HARDBOTTOM_P', 'SOFTBOTTOM_P', 'RUBBLE_P',
       'accession_url'],
      dtype='object')

In [6]:
cols_needed = [
    "PRIMARY_SAMPLE_UNIT",
    "latitude",
    "longitude",
    "YEAR",
    "REGION",
    "COVER_CAT_NAME",
    "HARDBOTTOM_P"
]

florida_clean = florida[cols_needed]

florida_clean.head()

,PRIMARY_SAMPLE_UNIT,latitude,longitude,YEAR,REGION,COVER_CAT_NAME,HARDBOTTOM_P
0,NaN,degrees_north,degrees_east,NaN,NaN,NaN,percent
1,1702.0,24.46499,-81.9823,2016.0,FLK,Eusmilia fastigiata,1
2,1702.0,24.46499,-81.9823,2016.0,FLK,Encrusting gorgonian,2
3,1702.0,24.46499,-81.9823,2016.0,FLK,Gorgonians,13
4,1702.0,24.46499,-81.9823,2016.0,FLK,Meandrina meandrites,1

In [7]:
florida_clean.shape

(13602, 7)

In [8]:
florida_clean.isnull().sum()

PRIMARY_SAMPLE_UNIT     1
latitude                0
longitude               0
YEAR                    1
REGION                  1
COVER_CAT_NAME         30
HARDBOTTOM_P           29
dtype: int64

### Dataset #2
## Puerto Rico Coral Reef Benthic Cover (CRCP Monitoring Data, 2014–2023)
---

The Puerto Rico Benthic Cover dataset includes 10,656 reef survey observations collected between 2014 and 2023 through NOAA’s Coral Reef Conservation Program. Each row represents one benthic category (like live coral or algae) measured at a specific reef site on a particular survey date. The dataset includes the site ID (`PRIMARY_SAMPLE_UNIT`), latitude and longitude (in decimal degrees), survey year (and month/day when available), region, the organism category (`COVER_CAT_NAME`), and the percent of hardbottom covered (`HARDBOTTOM_P`).

The main variable we care about is percent hardbottom cover, which is measured in percent (%). This tells us how much of the reef surface is covered by a certain organism type. For example, 30% live coral cover means that about one-third of the surveyed reef area was covered by living coral. In many reef systems, coral cover above about 30% is considered relatively healthy, while values below 10% often suggest significant degradation or limited recovery after stress events.

Since our research question looks at recovery patterns in live coral cover and how those patterns relate to algal cover, we use COVER_CAT_NAME to separate coral from algae and HARDBOTTOM_P to measure how dominant each group is. By combining location (site and region) with time (year), we can track how coral cover changes over time at different sites and see whether some reefs recover differently than others. This helps us explore whether higher algal cover is associated with weaker coral recovery after stress events.

**Variables We're Focusing On**

For this analysis, we’re mainly looking at location and habitat structure variables from the benthic dataset.
* Site ID (`PRIMARY_SAMPLE_UNIT`)
This is the unique identifier for each survey site. It allows us to group observations by location and track changes over time at the same site
* Latitude (degrees north) and Longitude (degrees east)
These tell us where each survey site is located. We’ll use them to look at spatial patterns and see whether habitat characteristics cluster in certain areas.
* Date (`YEAR`, `MONTH`, `DAY`)
These variables describe when the observation was recorded. YEAR allows us to evaluate long-term trends, while month/day could help identify seasonal patterns.
* Region 
This categorizes sites into broader geographic areas within Puerto Rico. It allows us to compare coral and algae cover across different parts of the island.
* `COVER_CAT_NAME`
This identifies the organism category being measured (e.g., coral, algae). This is central to our research question because we are specifically comparing coral vs. algae cover.
* Percent Cover (`HARDBOTTOM_P`)
This is the key outcome variable. It represents the percentage of hardbottom substrate covered by the organism listed in `COVER_CAT_NAME`.
It is measured as a percent (%), ranging theoretically from 0 to 100.
> * Values near 0% indicate little to no coverage.
> * Values near 100% indicate nearly complete coverage of the hardbottom area by that organism type.
> * Values outside 0–100% would be biologically impossible and indicate data issues.

By combining site location (latitude and longitude), region, time (year, month, day), organism category (coral vs. algae), and percent hardbottom cover, we can analyze how benthic community composition varies across Puerto Rico and over time. These variables allow us to examine both spatial differences between regions and temporal trends within sites. Rather than simply describing individual survey locations, this approach helps us identify broader patterns in coral and algae cover and assess how benthic communities may be shifting across space and time.


**Concerns and Limitations**

One major concern is sampling bias. Survey sites are not randomly distributed across all reef habitat — they are likely chosen based on accessibility, monitoring priorities, or ecological importance. This means results may not represent all reef areas equally.

Another limitation is temporal imbalance. Some sites may have been surveyed more frequently than others, and some years may have more complete coverage than others. This could affect trend analysis.

In addition, several numeric variables (like latitude, depth, and percent cover values) are stored as text and need to be converted before analysis. The first row of the dataset also contains unit labels instead of real data and must be removed during cleaning.

Finally, the dataset only covers about 10 years (2014–2023), not the full 20-year period in our research question. While it still captures recent bleaching and stress events, longer-term trends would require additional historical data.

In [9]:
## Load Raw Dataset
benthic_PR = pd.read_csv("data/00-raw/CRCP_Benthic_Cover_Puerto_Rico_07c6_3c17_78b6.csv")

benthic_PR.head()

,time,latitude,longitude,REGION,PRIMARY_SAMPLE_UNIT,STATION_NR,YEAR,MONTH,DAY,Date_UTC,...,DEPTH_STRAT,MIN_DEPTH,MAX_DEPTH,METERS_COMPLETED,COVER_CAT_CD,COVER_CAT_NAME,HARDBOTTOM_P,SOFTBOTTOM_P,RUBBLE_P,accession_url
0,UTC,degrees_north,degrees_east,NaN,NaN,NaN,NaN,NaN,NaN,UTC,...,NaN,m,m,m,NaN,NaN,percent,percent,percent,NaN
1,2019-07-18T00:00:00Z,18.14334361,-67.30063227,PRICO,6243.0,1.0,2019.0,7.0,18.0,2019-07-18T00:00:00Z,...,SHLW,8.839199717,9.448799698,15,BAR SUB.,Bare Substrate,29,0,0,https://accession.nodc.noaa.gov/0217139
2,2019-07-18T00:00:00Z,18.14334361,-67.30063227,PRICO,6243.0,1.0,2019.0,7.0,18.0,2019-07-18T00:00:00Z,...,SHLW,8.839199717,9.448799698,15,CYA SPE.,Cyanophyta spp,4,0,0,https://accession.nodc.noaa.gov/0217139
3,2019-07-18T00:00:00Z,18.14334361,-67.30063227,PRICO,6243.0,1.0,2019.0,7.0,18.0,2019-07-18T00:00:00Z,...,SHLW,8.839199717,9.448799698,15,DIC SPE.,Dictyota spp,18,0,0,https://accession.nodc.noaa.gov/0217139
4,2019-07-18T00:00:00Z,18.14334361,-67.30063227,PRICO,6243.0,1.0,2019.0,7.0,18.0,2019-07-18T00:00:00Z,...,SHLW,8.839199717,9.448799698,15,GOR GORG,Gorgonians,1,0,0,https://accession.nodc.noaa.gov/0217139

In [10]:
benthic_PR.shape

(10656, 34)

In [11]:
benthic_PR.columns

Index(['time', 'latitude', 'longitude', 'REGION', 'PRIMARY_SAMPLE_UNIT',
       'STATION_NR', 'YEAR', 'MONTH', 'DAY', 'Date_UTC', 'HABITAT_CD', 'STRAT',
       'RUGOSITY_CD', 'WTD_RUG', 'MEAN_RUG', 'MAPGRID_NR', 'SUB_REGION_NAME',
       'SUB_REGION_NR', 'ZONE_NAME', 'ZONE_NR', 'MPA_NAME', 'MPA_NR', 'ADMIN',
       'PROT', 'DEPTH_STRAT', 'MIN_DEPTH', 'MAX_DEPTH', 'METERS_COMPLETED',
       'COVER_CAT_CD', 'COVER_CAT_NAME', 'HARDBOTTOM_P', 'SOFTBOTTOM_P',
       'RUBBLE_P', 'accession_url'],
      dtype='object')

In [12]:
cols_to_keep = [
    "PRIMARY_SAMPLE_UNIT",
    "latitude",
    "longitude",
    "YEAR",
    "MONTH",
    "DAY",
    "REGION",
    "COVER_CAT_NAME",
    "HARDBOTTOM_P"
]

benthic_PR = benthic_PR[[col for col in cols_to_keep if col in benthic_PR.columns]]

In [13]:
benthic_PR.head()

,PRIMARY_SAMPLE_UNIT,latitude,longitude,YEAR,MONTH,DAY,REGION,COVER_CAT_NAME,HARDBOTTOM_P
0,NaN,degrees_north,degrees_east,NaN,NaN,NaN,NaN,NaN,percent
1,6243.0,18.14334361,-67.30063227,2019.0,7.0,18.0,PRICO,Bare Substrate,29
2,6243.0,18.14334361,-67.30063227,2019.0,7.0,18.0,PRICO,Cyanophyta spp,4
3,6243.0,18.14334361,-67.30063227,2019.0,7.0,18.0,PRICO,Dictyota spp,18
4,6243.0,18.14334361,-67.30063227,2019.0,7.0,18.0,PRICO,Gorgonians,1

In [14]:
benthic_PR["YEAR"].value_counts().sort_index()

YEAR
2014.0    2794
2016.0    1721
2017.0     266
2019.0    1673
2021.0    1962
2023.0    2239
Name: count, dtype: int64

**Check Tidy Structure**

The dataset is already in long (tidy) format because each row represents one benthic category observation at a specific site and date. Each column represents a single variable (e.g., depth, percent cover, region).
**_BUT_**, this does not mean it is *clean*.

In [15]:
benthic_PR.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10656 entries, 0 to 10655
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   PRIMARY_SAMPLE_UNIT  10655 non-null  float64
 1   latitude             10656 non-null  object
 2   longitude            10656 non-null  object
 3   YEAR                 10655 non-null  float64
 4   MONTH                10655 non-null  float64
 5   DAY                  10655 non-null  float64
 6   REGION               10655 non-null  object
 7   COVER_CAT_NAME       10655 non-null  object
 8   HARDBOTTOM_P         10656 non-null  object
dtypes: float64(4), object(5)
memory usage: 749.4+ KB

In [16]:
print("Number of rows:", benthic_PR.shape[0])
print("Number of columns:", benthic_PR.shape[1])

Number of rows: 10656
Number of columns: 9

In [17]:
## Convert Data Types

numeric_cols = [
    "latitude",
    "longitude",
    "YEAR",
    "MONTH", 
    "DAY",
    "HARDBOTTOM_P"
]

for col in numeric_cols:
    benthic_PR[col] = pd.to_numeric(benthic_PR[col], errors="coerce")

In [18]:
## Missing Data Analysis

missing_counts = benthic_PR.isna().sum()
missing_percent = benthic_PR.isna().mean() * 100

pd.DataFrame({
    "Missing Count": missing_counts,
    "Missing %": missing_percent
}).sort_values("Missing %", ascending=False)

                     Missing Count  Missing %
PRIMARY_SAMPLE_UNIT              1   0.009384
latitude                         1   0.009384
longitude                        1   0.009384
YEAR                             1   0.009384
MONTH                            1   0.009384
DAY                              1   0.009384
REGION                           1   0.009384
COVER_CAT_NAME                   1   0.009384
HARDBOTTOM_P                     1   0.009384

In [19]:
outliers = benthic_PR[
    (benthic_PR["HARDBOTTOM_P"] < 0) |
    (benthic_PR["HARDBOTTOM_P"] > 100)
]

outliers

Empty DataFrame
Columns: [PRIMARY_SAMPLE_UNIT, latitude, longitude, YEAR, MONTH, DAY, REGION, COVER_CAT_NAME, HARDBOTTOM_P]
Index: []

No biologically impossible percent values (<0% or >100%) were seen.

In [20]:
benthic_PR["HARDBOTTOM_P"].describe()

count    10655.000000
mean         6.681933
std         10.735646
min          0.000000
25%          1.000000
50%          2.000000
75%          7.000000
max         98.000000
Name: HARDBOTTOM_P, dtype: float64

**Cleaning Strategy**

Columns that are entirely missing/ not being used for our research question (e.g., ZONE_NAME, MPA_NAME, PROT) are going to be dropped because they contain no usable information (as done above). Numeric variables stored as text were converted to numeric format. (also done above)

Because HARDBOTTOM_P is our primary outcome variable, rows missing this value cannot be used for analysis and will be removed.
We also drop rows missing essential identifiers (site, year, region, category).

*We keep rows with missing MONTH or DAY if YEAR is present, since yearly trends are sufficient for our main analysis.*

In [21]:
benthic_clean_PR = benthic_PR.dropna(
    subset=[
        "PRIMARY_SAMPLE_UNIT",
        "YEAR",
        "REGION",
        "COVER_CAT_NAME",
        "HARDBOTTOM_P"
    ]
)

In [23]:
benthic_clean_PR.head()

,PRIMARY_SAMPLE_UNIT,latitude,longitude,YEAR,MONTH,DAY,REGION,COVER_CAT_NAME,HARDBOTTOM_P
1,6243.0,18.143344,-67.300632,2019.0,7.0,18.0,PRICO,Bare Substrate,29.0
2,6243.0,18.143344,-67.300632,2019.0,7.0,18.0,PRICO,Cyanophyta spp,4.0
3,6243.0,18.143344,-67.300632,2019.0,7.0,18.0,PRICO,Dictyota spp,18.0
4,6243.0,18.143344,-67.300632,2019.0,7.0,18.0,PRICO,Gorgonians,1.0
5,6243.0,18.143344,-67.300632,2019.0,7.0,18.0,PRICO,Halimeda spp,8.0

In [ ]:
benthic_clean_PR.describe()

In [ ]:
benthic__clean_PR.to_csv("data/02-processed/benthic_cover_PR_cleaned.csv", index=False)

### Dataset #2
 as above, add any more copies of this that you need to given how many datasets you have

### Dataset #2
 as above, add any more copies of this that you need to given how many datasets you have

## Results

### Exploratory Data Analysis

Instructions: replace the words in this subsection with whatever words you need to setup and preview the EDA you're going to do.   

Please explicitly load the fully wrangled data you will use from `data/02-processed`.  This is a good idea rather than forcing people to re-run the data getting / wrangling cells above.  Sometimes it takes a long time to get / wrangle data compared to reloading the fixed up dataset.

Carry out whatever EDA you need to for your project in the code cells below.  Because every project will be different we can't really give you much of a template at this point. But please make sure you describe the what and why in text here as well as providing interpretation of results and context.

Please note that you should consider the use of python modules in your work.  Any code which gets called repeatedly should be modularized. So if you run the same pre-processing, analysis or visualiazation on different subsets of the data, then you should turn that into a function or class.  Put that function or class in a .py file that lives in `modules/`.  Import the module you made and use it to get your work done.  For reference see `get_raw()` which is inside `modules/get_data.py`.

#### Section 1 of EDA - please give it a better title than this

Some more words and stuff.  Remember notebooks work best if you interleave the code that generates a result with properly annotate figures and text that puts these results into context.

In [ ]:
## YOUR CODE HERE
## FEEL FREE TO ADD MULTIPLE CELLS PER SECTION

#### Section 2 of EDA if you need it  - please give it a better title than this

Some more words and stuff.  Remember notebooks work best if you interleave the code that generates a result with properly annotate figures and text that puts these results into context.

In [ ]:
## YOUR CODE HERE
## FEEL FREE TO ADD MULTIPLE CELLS PER SECTION

#### Section 3 of EDA if you need it  - please give it a better title than this

Some more words and stuff.  Remember notebooks work best if you interleave the code that generates a result with properly annotate figures and text that puts these results into context.

In [ ]:
## YOUR CODE HERE
## FEEL FREE TO ADD MULTIPLE CELLS PER SECTION

#### Section 4 of EDA if you need it  - please give it a better title than this

Some more words and stuff.  Remember notebooks work best if you interleave the code that generates a result with properly annotate figures and text that puts these results into context.

In [ ]:
## YOUR CODE HERE
## FEEL FREE TO ADD MULTIPLE CELLS PER SECTION

#### Section 5 of EDA if you need it  - please give it a better title than this

Some more words and stuff.  Remember notebooks work best if you interleave the code that generates a result with properly annotate figures and text that puts these results into context.

In [ ]:
## YOUR CODE HERE
## FEEL FREE TO ADD MULTIPLE CELLS PER SECTION

## Ethics

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your proposal feedback

## Team Expectations

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your proposal feedback

## Project Timeline Proposal

Instructions: Replace this with your timeline.  **PLEASE UPDATE your Timeline!** No battle plan survives contact with the enemy, so make sure we understand how your plans have changed.  Also if you have lost points on the previous checkpoint fix them